name: Bypass Cloudflare for Github Action
description: Manages IP whitelisting in Cloudflare to make sure GitHub Action runner can access a Cloudflare-proxied host.
branding:
  icon: shield-off
  color: blue
inputs:
  cf_account_id:
    description: "Cloudflare Account ID"
    required: true
  cf_zone_id:
    description: "Cloudflare Zone ID"
    required: true
  cf_api_token:
    description: "Cloudflare API Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Get Runner Public IP
      shell: bash
      id: get_ip
      run: |
        result=$(curl https://ipinfo.io/json)
        ip=$(echo $result | jq -r '.ip')
        echo "public_ip=$ip" >> $GITHUB_ENV
    - name: Check Existing CF IP List (Lists API)
      shell: bash
      id: check_ip_list
      run: |
        list_name="bypass_cloudflare_for_github_action_list"
        response=$(curl --request GET \
          --url "https://api.cloudflare.com/client/v4/accounts/${{ inputs.cf_account_id }}/rules/lists" \
          --header 'Content-Type: application/json' \
          --header "Authorization: Bearer ${{ inputs.cf_api_token }}")

        list_id=$(echo "$response" | jq -r --arg name "$list_name" '.result[] | select(.name == $name) | .id' | head -n1)

        echo "list_created=false" >> $GITHUB_ENV

        if [ -n "$list_id" ] && [ "$list_id" != "null" ]; then
          echo "Found existing list '$list_name' with ID: $list_id"
          echo "list_exists=true" >> $GITHUB_ENV
          echo "list_id=$list_id" >> $GITHUB_ENV
          echo "list_id=$list_id" >> $GITHUB_OUTPUT
        else
          echo "List '$list_name' not found. It will be created."
          echo "list_exists=false" >> $GITHUB_ENV
          echo "list_id=" >> $GITHUB_ENV
        fi
    - name: (Setup only) Create CF IP List (Lists API)
      shell: bash
      id: create_ip_list
      if: env.list_exists != 'true'
      run: |
        list_name="bypass_cloudflare_for_github_action_list"
        list_description="Generated by xiaotianxt/bypass-cloudflare-for-github-action. Empty list by default."
        
        body=$(jq -n --arg name "$list_name" --arg desc "$list_description" '{kind: "ip", name: $name, description: $desc}')
        
        response=$(curl --request POST \
          --url "https://api.cloudflare.com/client/v4/accounts/${{ inputs.cf_account_id }}/rules/lists" \
          --header 'Content-Type: application/json' \
          --header "Authorization: Bearer ${{ inputs.cf_api_token }}" \
          --data "$body")
        
        echo "Response: $response"
        list_id=$(echo $response | jq -r '.result.id')
        
        if [ "$list_id" = "null" ] || [ -z "$list_id" ]; then
          echo "Error: Failed to create list. Response: $response"
          exit 1
        fi
        
        echo "Created List with ID: $list_id"
        echo "list_id=$list_id" >> $GITHUB_ENV
        echo "list_id=$list_id" >> $GITHUB_OUTPUT
        echo "list_exists=true" >> $GITHUB_ENV
        echo "list_created=true" >> $GITHUB_ENV
    - name: (Setup only) Create Bypass Rule for IP List (Rulesets API)
      shell: bash
      id: create_waf_rule
      if: env.list_created == 'true'
      run: |
        zone_id="${{ inputs.cf_zone_id }}"
        list_name="bypass_cloudflare_for_github_action_list"
        
        if [ -z "$zone_id" ]; then
          echo "Error: cf_zone_id is required for setup mode"
          exit 1
        fi
        
        # Following documentation here: https://developers.cloudflare.com/waf/custom-rules/create-api/
        # Get the entry point ruleset for http_request_firewall_custom phase
        phase_name="http_request_firewall_custom"
        response=$(curl --request GET \
          --url "https://api.cloudflare.com/client/v4/zones/$zone_id/rulesets/phases/$phase_name/entrypoint" \
          --header 'Content-Type: application/json' \
          --header "Authorization: Bearer ${{ inputs.cf_api_token }}" \
          --write-out "\n%{http_code}" \
          --silent)
        
        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | sed '$d')
        
        if [ "$http_code" = "200" ]; then
          # Ruleset exists, extract ruleset ID and add rule to it
          ruleset_id=$(echo "$body" | jq -r '.result.id')
          echo "Found existing ruleset with ID: $ruleset_id"
          
          # Build rule payload using jq
          expression="ip.src in \$$list_name"
          rule_payload=$(jq -n \
            --arg desc "Bypass for GitHub Actions" \
            --arg expr "$expression" \
            '{
              description: $desc,
              expression: $expr,
              action: "skip",
              action_parameters: {
                phases: ["http_request_firewall_managed", "http_ratelimit", "http_request_sbfm"],
                ruleset: "current"
              },
              position: {
                index: 1
              }
            }')
          
          response=$(curl --request POST \
            --url "https://api.cloudflare.com/client/v4/zones/$zone_id/rulesets/$ruleset_id/rules" \
            --header 'Content-Type: application/json' \
            --header "Authorization: Bearer ${{ inputs.cf_api_token }}" \
            --data "$rule_payload")
          
          echo "Response: $response"
          rule_id=$(echo "$response" | jq -r '.result.id')
          
          if [ "$rule_id" = "null" ] || [ -z "$rule_id" ]; then
            echo "Error: Failed to create rule. Response: $response"
            exit 1
          fi
          
          echo "Created WAF rule with ID: $rule_id"
        elif [ "$http_code" = "404" ]; then
          # Ruleset doesn't exist, create it with the rule
          echo "Ruleset does not exist, creating new ruleset with rule"
          
          # Build ruleset payload with rule using jq
          expression="ip.src in \$$list_name"
          ruleset_payload=$(jq -n \
            --arg desc "Bypass for GitHub Actions" \
            --arg expr "$expression" \
            '{
              kind: "zone",
              name: "default",
              phase: "http_request_firewall_custom",
              rules: [{
                description: $desc,
                expression: $expr,
                action: "skip",
                action_parameters: {
                  phases: ["http_request_firewall_managed", "http_ratelimit", "http_request_sbfm"],
                  ruleset: "current"
                },
                position: {
                  index: 1
                }
              }]
            }')
          
          response=$(curl --request POST \
            --url "https://api.cloudflare.com/client/v4/zones/$zone_id/rulesets" \
            --header 'Content-Type: application/json' \
            --header "Authorization: Bearer ${{ inputs.cf_api_token }}" \
            --data "$ruleset_payload")
          
          echo "Response: $response"
          ruleset_id=$(echo "$response" | jq -r '.result.id')
          
          if [ "$ruleset_id" = "null" ] || [ -z "$ruleset_id" ]; then
            echo "Error: Failed to create ruleset. Response: $response"
            exit 1
          fi
          
          echo "Created ruleset with ID: $ruleset_id"
        else
          echo "Error: Unexpected response when getting ruleset. HTTP code: $http_code, Response: $body"
          exit 1
        fi
    - name: Add Runner IP to List (Lists API)
      shell: bash
      id: add_ip_to_list
      run: |
        list_id="${{ env.list_id }}"
        ip="${{ env.public_ip }}"
        
        if [ -z "$list_id" ] || [ -z "$ip" ]; then
          echo "Error: Missing required variables"
          exit 1
        fi
        
        payload_file=$(mktemp)
        jq -nc --arg ip "$ip" --arg comment "GitHub Actions runner" '[{ip: $ip, comment: $comment}]' > "$payload_file"
        echo "Replacing list $list_id with single IP: $ip"
        echo "Payload file contents:" && cat "$payload_file"
        response=$(curl --silent --show-error --write-out '\n%{http_code}' \
          --request PUT \
          --url "https://api.cloudflare.com/client/v4/accounts/${{ inputs.cf_account_id }}/rules/lists/$list_id/items" \
          --header 'Content-Type: application/json' \
          --header "Authorization: Bearer ${{ inputs.cf_api_token }}" \
          --data @"$payload_file")
        rm -f "$payload_file"
        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | sed '$d')
        echo "HTTP status: $http_code"
        echo "Response body: $body"
        
        if [ "$http_code" != "200" ]; then
          echo "Error: Failed to add IP to list. Response: $body"
          exit 1
        fi

        operation_id=$(echo "$body" | jq -r '.result.operation_id // empty')
        if [ -n "$operation_id" ]; then
          echo "Operation ID: $operation_id"
        fi
        echo "List $list_id now contains only $ip"
    - name: Clear List
      uses: gacts/run-and-post-run@v1
      with:
        post: |
          list_id="${{ env.list_id }}"
          echo "Clearing list $list_id"
          curl --request PUT \
            --url "https://api.cloudflare.com/client/v4/accounts/${{ inputs.cf_account_id }}/rules/lists/$list_id/items" \
            --header 'Content-Type: application/json' \
            --header "Authorization: Bearer ${{ inputs.cf_api_token }}" \
            --data '[]' \
            || exit 1